---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: property
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/property
      interval: 1m0s
      sourceRef:
        kind: GitRepository
        name: property
        namespace: flux-system
      version: 1.0.0
  install:
    remediation:
      retries: 3
  interval: 5m0s
  releaseName: property
  targetNamespace: devops-property
  timeout: 2m0s
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.20"
    nameOverride: ""
    fullnameOverride: ""
    replicaCount: 1
    serviceAccount: 
      create: true 
      annotations: {} 
      name: ""
    service:
      type: ClusterIP
      port: 80
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: property
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fernandokarnagi/chart-property
